name: Branch

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint Projects
        run: npx nx run-many --target=lint

      - name: Build Projects
        run: npx nx run-many --target=lint

      - name: Build Docker Image
        run: npx nx run bot:docker-build
