name: Tag

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint Projects
        run: npx nx run-many --target=lint

      - name: Build Projects
        run: npx nx run-many --target=build

      - name: Build Docker Image
        run: docker build --file apps/bot/Dockerfile . -t discord-bot-app:${{ env.GITHUB_REF }}

      - name: Log into Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to Github Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/discord-bot-app:${{ env.GITHUB_REF }}
